name: test
on: [push]

jobs:
  server-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [11.x]
    steps:
      - uses: actions/checkout@master

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Installing Dependencies
        working-directory: ./server
        run: npm i

      - name: Running Tests
        working-directory: ./server
        run: npm test
  client-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [11.x]
    steps:
      - uses: actions/checkout@master

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Installing Dependencies
        working-directory: ./client
        run: npm i

      - name: Running Tests
        working-directory: ./client
        run: npm test