name: Test
on: [push]

jobs:
  server-tests:
    working-directory: ./server
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [11.x]
    steps:
      - uses: actions/checkout@master

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('server/package-lock.json') }}

      - name: Installing Dependencies
        run: npm i

      - name: Running Tests
        run: npm test